from flask import Flask, request, jsonify, send_from_directory
import os
from transformers import RobertaTokenizer, RobertaForQuestionAnswering, pipeline
import torch
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

# Initialize message history as an empty list
message_history = []


@app.route('/')
def index():
    return send_from_directory(os.path.join(app.root_path, ''), 'index.html')


@app.route('/query', methods=['POST'])
def process_query():
    global message_history  # Use global variable to store message history
    # load QA model API
    get_answer = pipeline(task="question-answering", model="MattNandavong/QA-roberta-model3")
    #context list 
    contextList = [
        # ERN-Enrol and applying
        {"topic": "We can potentially offer students unit exemptions for our undergraduate courses, based on diploma and higher education qualifications undertaken within the last 10 years. Swinburne Online takes domestic students for both degrees and TAFE diplomas from anywhere in Australia. International students are also accepted for our degrees. enrolments close approximately 10 days before the start of each teaching period. Our teaching periods run three times a year, from March to June, July to October and November to February. It is expected that applicants have proficient English skills. We recommend the below levels in an English language test such as IELTS or TOEFL to ensure you are successful at university It is expected that applicants have proficient English skills. You should have a bachelor degree or equivalent (at least three years) studied in English, or have completed year 12 English in Australia. You must meet the below levels in an English language test such as IELTS, ISLPR or PEAT. recent Year 12 students must apply through VTAC for Swinburne courses for the March intake. However you may apply for Swinburne Online's July or November intakes. If you are unsure which qualification is most relevant to you, speak to a Course Consultant for some advice or see our Levels of Education FAQ section. If you’re unsure about whether you’ll be eligible to study with Swinburne, it’s definitely worth calling our team of course consultants on 1300 069 765 or +61 3 9956 0777 if you are calling from overseas. Our team of Course Consultants will normally get in touch with you within two working days of you submitting your application with an outcome. Students wishing to study with us, simply need to complete an application form and submit it to Swinburne Online. Because you will be studying a degree online, all of our support systems are available over the phone or online. Yes, Swinburne Online accept applications from international students for our higher education courses. You can study at Swinburne Online from any state or territory in Australia"},
        # FFA - Fee and Financial Assistance
        {"topic": "Gaining a scholarship for a master's degree in Australia can be competitive. To obtain full funding for a master's degree in Australia, you can apply for a scholarship through the Online Australia Scholarships Information System. Yes, you will need to pay for masters degree in Australia. You can pay for your postgraduate study by CSP, HECS-HELP and FEE-HELP loans schemes. There's no set limit on the number of degrees you can study using HECS. Yes, the Higher Education Loan Program (HELP) is the same as the Higher Education Contribution Scheme (HECS). Yes, you can obtain a student loan for a master's degree in Australia. postgraduate study is covered by HECS. There is no interest charged on a HECS HELP loans. get important information about the VET Student Loan Program via VET Student Loans Information Booklet. find out more about VET Student Loans at https://www.swinburneonline.edu.au/fees/vet-student-loans/ Student Amenities Help fee allow student to have access with 34 institute’s amenties. HECS-HELP is how eligible students can pay their student contribution amount. Commonwealth Supported Place(CSP) pay part of the course fees. If you do not pay your fees by the due date you may be cancelled from your degree. Postgraduate Degrees financial assistance is only for Australian citizens and permanent residents. International students are not eligible for any financial assistance from the Australian government. VET Student Loans (VSL) only approve for eligible students. If you have VSL you can withdraw from your course before census date. Course cost may vary slightly depending on which units you choose. You can repay HELP loan with the Australian Tax system. Swinburne offer either HECS-HELP or FEE-HELP to Australian citizens and permanent humanitarian visa-holders for all of our university courses. No. Once you have finished your Introductory Skill Set course, you can apply for VSL to apply to the Diploma. You need to apply VSL before census date. There are currently no Commonwealth Supported Places(CSP) available to postgraduate students."},
        # Studying Online
        {"topic": "All of our assessments at Swinburne Online are submitted online. Online Student will receive the same accredited qualification as a Swinburne University of Technology on-campus student. You don’t need to go to campus we provide everything you need online. You will be studying with other 20-25 online student in class. You can study online from anywhere in Australia that have access to internet. You can get assesment support from advisors or via Studiosity.Exams are held in Australian capital cities or regional centres based on the number of candidates in that location. the difference between degrees and diploma is the diploma is practical qualification and a degree is more academic courses. Online education utilises breakthrough web technologies to deliver academic courses.a virtual classroom is the online space where your learning will take place. The tools you need to complete your qualification or online course is computer, speakers or headphones, web camera, microphone and internet.the main differences between online, on-campus and distance education is the aviability to access to the course. an online qualification is the exact same qualification as a student at Swinburne University of Technology. credit for previous studies will appear on your academic transcript. online study material is available for you from the beginning of each teaching period and you can work through it in the hours that suit you. Time management could help you stay on track of your study. here is how exams work Online student required to have online exams.You can communicate with students using the discussion boards. you cwill receive student card"},
        # MBA
        {"topic": "You need a Bachelor degree to do MBA programs. the duration of an MBA program can range from 1 to 2 years. You should do MBA because An MBA is suitable for anyone looking to enhance their business knowledge and leadership skills. Studying an MBA has the potential for a higher salary. An MBA teaches a wide range of business and management skills. The time to complete a part-time MBA can vary significantly based on the program and individual progress. A weekend MBA is a specialised MBA program designed for working professionals who can attend classes on weekends. A full-time MBA program typically takes about two years to complete. The number of hours per week for an MBA can vary based on the program and the number of units or courses taken. Yes, part-time MBA programs are available for individuals. Yes, you can complete an MBA while working full time. MBA could be too advance for who have not studied at a tertiary level before. MBA Swinburne Online could provide  valuable network of like-minded business professionals. Your Master of Business Administration will prepare you the decisive vision and professional agility needed to stand apart from your peers. Swinburne University’s MBA has a Tier-1 rating and is in the top Online MBAs in CEO Magazine's 2022 Global Rankings. As a business leader/owner MBA will enhance your professional skillset and give you the tools to grow your customer base, output and profit margin. jop opportunity required MBA are Senior Associate, Strategic Manager, Executive General Manager, Managing Director, Chief Operating Officer, Chief Executive Officer (CEO)."},
        # TAFE
        {"topic": "Technical and Further Education (TAFE) is the term used to describe certain state-administered education institutions. the entry requirements for TAFE Business courses  you need to meet the specific entry criteria for your course. There are no exams for Swinburne Online’s TAFE Business courses. When you study a TAFE course with Swinburne Online all of your study will happen in Canvas. There are no exams for Swinburne Online’s TAFE Business courses. most of your learning materials are included with a free license provided to you by Swinburne Online. Yes, some of your units in the Diploma of Nursing course require you to sit exams. Diploma of Nursing changing is because the federal Government announced changes to the current national health training package. Swinburne Online be releasing the new Diploma of Nursing in early 2022. The learning outcomes will remain the same, with students gaining a nationally recognised qualification. The changes follow industry review and aim to better align student outcomes. You need to meet the specific criterea as requirement for the Diploma of nursing. THe diploma of Nursing study will happen in Canvas. textbooks, nursing kit and a uniform is a required materials you need for the Diploma of Nuring course. "},
        # Technology
        {"topic": "The Tableau Desktop Certified Specialist certification is an industry-recognised qualification that demonstrates your comprehensive knowledge and abilities in Tableau application. Devices you need to complete your qualification are computer, speakers or headphones, web camera, microphone and internet.the benefits of acquiring a Tableau certification are demonstrate and validate your competency to the market and Tableau directory. Most of the software are provided. most of your learning materials are included with a free license provided to you by Swinburne Online."},
        # Level of Education
        {"topic": "Vocational Education and Training (VET) is focused on providing students with specific job related and technical skills. Undergraduate study is a term used to describe formal, accredited tertiary education achievements. Technical and Further Education (TAFE) is the term used to describe certain state-administered education institutions. Postgraduate study is a term generally used to describe tertiary education courses available to students who have already completed a bachelor degree or have significant relevant work experience. Online education utilises breakthrough web technologies to deliver academic courses. Higher education encompasses Bachelor level degrees and above and is offered by universities. Distance education (sometimes known as learning by correspondence) is a broad term that describes education delivered to a student who is in a separate location to the source of the academic content. Honours Degree generally requiring you to compete a research project and submit a thesis. A Doctor of Philosophy, or PhD, is a globally recognised qualification that’s considered the highest postgraduate achievement an individual can earn.  Masters Degree allows you to become a specialist in your chosen field. A Graduate Diploma will allow you to complete specialisation studies in a smaller amount of time and at a reduced cost of a Masters degree. Completing a Graduate Certificate will help you upgrade your qualifications or give you advanced practical skills required in specialist industries. A double degree is a university degree where you study two single degrees at the same time, giving you the option of specialising in two different fields. Completing a Diploma or Advanced Diploma certificate will give you practical skills for work as well as the opportunity to progress to another qualification. Certificates are the most basic qualification available to secondary school students and beyond. Bachelor degrees are offered by universities and are presented to you when you complete an undergraduate course of study."},
        # STARS
        {"topic": "All students enrolled into the STARS program will receive a $900 Stipend to assist with the cost of their study or professional placement. The STARS professional placements are part of the required professional placements in your course. They are not extra placements. You will be able to complete your final two placements through the STARS program at your school. You will also be able to continue with PTT across the year. The STARS modules remain open all the time, so you will be able to complete the module work at a time that suits you. There are five modules, each with approximately 1.5–2 hours of reading and activities. Allow 7.5–10 hours in total to complete the STARS modules. You will receive a certificate of completion outlining your completion of the STARs program. all costs associated with travel or accommodation will be incurred by the pre-service teacher. Victorian Department of Education and Training (DET) will be supporting Swinburne to access and source the placement schools on your behalf. The STARS program placement schools can be in regional and rural or low socioeconomic schools in Victoria that will be selected by Swinburne, with pre-service teachers matched to schools. You can organise a placement in a STARS-approved school setting with Victorian Department of Education and Training (DET). During the year the program runs (mid-year 2022 to mid-year 2023), you must undertake both remaining placements (or the one remaining), in your course during this time. STARS program will run alongside your current units of study. pre-service teachers can partake in the STARS program for 2022–2023 year is only open to 75 students and therefore a rigorous selection process will take place. The STARS program commences mid-year 2022 (TP2, Q3)."},
        # Short course
        {"topic": "These courses have been significantly discounted to allow you to complete study during the next 6 months and support your future employment opportunities. the entry criteria is Undergraduate Certificate of Information and Communication Technology. You will study COS10005, ICT10001, INF10002, and INF10003. Units you complete prior to 1 December are discounted.  If you wish to continue studying the course after 1 December 2020, you will be eligible for a Commonwealth Supported Place for the rest of your studies. you need to enrol in at least a graduate certificate level qualification before enrol in a Profestional Certificates. Professional Certificates are generally the first two units of a Graduate or Undergraduate Certificate and provide you with solid introductory knowledge, as well as contributing to the higher degree should you wish to continue studying later. you can choose to complete your studies after the first two units and exit with a University-accredited Professional Certificate. you can choose to complete your studies after the first two units and exit with a University-accredited Professional Certificate. Your discounted fee will be applied at the time of enrolment."}
    ]
    
    # load context
    context = "We can potentially offer students unit exemptions for our undergraduate courses, based on diploma and higher education qualifications undertaken within the last 10 years. Swinburne Online takes domestic students for both degrees and TAFE diplomas from anywhere in Australia. International students are also accepted for our degrees. enrolments close approximately 10 days before the start of each teaching period. Our teaching periods run three times a year, from March to June, July to October and November to February. It is expected that applicants have proficient English skills. We recommend the below levels in an English language test such as IELTS or TOEFL to ensure you are successful at university It is expected that applicants have proficient English skills. You should have a bachelor degree or equivalent (at least three years) studied in English, or have completed year 12 English in Australia. You must meet the below levels in an English language test such as IELTS, ISLPR or PEAT. recent Year 12 students must apply through VTAC for Swinburne courses for the March intake. However you may apply for Swinburne Online's July or November intakes. If you are unsure which qualification is most relevant to you, speak to a Course Consultant for some advice or see our Levels of Education FAQ section. If you’re unsure about whether you’ll be eligible to study with Swinburne, it’s definitely worth calling our team of course consultants on 1300 069 765 or +61 3 9956 0777 if you are calling from overseas. Our team of Course Consultants will normally get in touch with you within two working days of you submitting your application with an outcome. Students wishing to study with us, simply need to complete an application form and submit it to Swinburne Online. Because you will be studying a degree online, all of our support systems are available over the phone or online. Yes, Swinburne Online accept applications from international students for our higher education courses. You can study at Swinburne Online from any state or territory in Australia"
    # load data query from frontend
    data = request.get_json()
    query = data['query']
    topic = data['topic']
    #generate topic base topic choosen
    context = contextList[topic]['topic']

    # Load the text classification pipeline
    classifier = pipeline("text-classification", model="MattNandavong/Swin_text_classification_4")
    # detect out of scope topic 'LABEL_17'
    topic_identify = classifier(query)

    if topic_identify[0]['label'] == "LABEL_17":
        answer = "This question is out of Swinburne scope."
    else: 
        # get the most likely answer
        answer = get_answer(context=context, question=query)['answer']

    # Add user query and model answer to message history
    message_history.append({'user_query': query, 'model_answer': answer})

    # Return both answer and message history
    return jsonify({'answer': answer, 'message_history': message_history})


if __name__ == '__main__':
    app.run(debug=True)
